# Evn

In [ ]:
# imports
import argparse
import os
import random
import shutil
import json
import zipfile
import math
import copy
import collections
import re

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
# import sentencepiece as spm
import tensorflow as tf
import tensorflow.keras.backend as K

from tqdm.notebook import tqdm, trange

In [ ]:
# 환경 설정
args = {
    # random seed value
    "seed": 1234
}
args = argparse.Namespace(**args)

print(args)

Namespace(seed=1234)


In [ ]:
# random seed 설정
random.seed(args.seed)
np.random.seed(args.seed)
tf.random.set_seed(args.seed)

In [ ]:
# gpu 사용량 확인
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



# softmax

In [ ]:
x = np.random.randn(5,3)
x
# sample이 5개

array([[ 0.47143516, -1.19097569,  1.43270697],
       [-0.3126519 , -0.72058873,  0.88716294],
       [ 0.85958841, -0.6365235 ,  0.01569637],
       [-2.24268495,  1.15003572,  0.99194602],
       [ 0.95332413, -2.02125482, -0.33407737]])

In [ ]:
exp_x = np.exp(x)
exp_x

array([[1.6022921 , 0.30392458, 4.19002612],
       [0.73150451, 0.48646577, 2.42823083],
       [2.36218825, 0.52912874, 1.01582021],
       [0.10617305, 3.15830574, 2.69647677],
       [2.59431919, 0.13248911, 0.71599839]])

In [ ]:
sum_x = np.sum(exp_x, axis = -1)
sum_x = np.expand_dims(sum_x , axis = -1)

a = sum_x.reshape(5,1)
a.shape

sum_x.shape
# 분모 구했고
# 이제 나눠야지

(5, 1)

In [ ]:
y_pred = exp_x / sum_x
y_pred


array([[0.26283272, 0.04985441, 0.68731287],
       [0.200621  , 0.13341715, 0.66596185],
       [0.60458288, 0.1354262 , 0.25999092],
       [0.01781141, 0.52983212, 0.45235646],
       [0.75354774, 0.03848288, 0.20796938]])

In [ ]:
np.sum(y_pred, axis = -1)
#확인 ㅇㅋ

array([1., 1., 1., 1., 1.])

In [ ]:
tf.nn.softmax(x)
# 값 같네!

<tf.Tensor: shape=(5, 3), dtype=float64, numpy=
array([[0.26283272, 0.04985441, 0.68731287],
       [0.200621  , 0.13341715, 0.66596185],
       [0.60458288, 0.1354262 , 0.25999092],
       [0.01781141, 0.52983212, 0.45235646],
       [0.75354774, 0.03848288, 0.20796938]])>

In [ ]:
log_y_pred = np.log(y_pred)
log_y_pred

array([[-1.33623748, -2.99864834, -0.37496568],
       [-1.60633773, -2.01427457, -0.40652289],
       [-0.50321652, -1.99932844, -1.34710856],
       [-4.02791575, -0.63519507, -0.79328478],
       [-0.28296291, -3.25754186, -1.5703644 ]])

In [ ]:
y_true = np.array([
                   [0,0,1],
                   [1,0,0],
                   [0,0,1],
                   [0,1,0],
                   [1,0,0]
])

In [ ]:
ce = - (y_true * log_y_pred)
ce

array([[0.        , 0.        , 0.37496568],
       [1.60633773, 0.        , 0.        ],
       [0.        , 0.        , 1.34710856],
       [0.        , 0.63519507, 0.        ],
       [0.28296291, 0.        , 0.        ]])

In [ ]:
ce1 = np.sum(ce, axis = -1)
ce1

array([0.37496568, 1.60633773, 1.34710856, 0.63519507, 0.28296291])

In [ ]:
np.mean(ce1)

0.8493139901628297

In [ ]:
tf.keras.losses.CategoricalCrossentropy()(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float64, numpy=0.8493140339851379>

In [ ]:
# 확률 구하기 전 값가지고 바로 하겠다
# from_logit을 통해 x에서 바로 구하겠다
tf.keras.losses.CategoricalCrossentropy(from_logits=True)(y_true, x)

<tf.Tensor: shape=(), dtype=float64, numpy=0.8493140339851379>

In [ ]:
# 굳이 ont-hot vector로 안만들어줘도 sparse categorical cross entropy로 한다다

tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)([2,0,2,1,0], x)


<tf.Tensor: shape=(), dtype=float64, numpy=0.8493140339851379>